### ISSUE TITLE
DO NOT WORK ON THIS - Front End - Split form into Two Sections & add 'Create Account' function - Create content

### ISSUE THREAD

**Issue by katmartel** [jpabadir/pace-c#185]
Based on the static form from last week's sprint, remove the 'Submit' button from that section. When the 'next' button is clicked, go to another page for the user to fill in information to create an account. Once the user clicks 'submit', that information will be sent to the database.
Fix Email and User type fields, add ranked skills (3 input fields, the drop-down options should be hardcoded).

**Comment by jpabadir** [comment]
Closing as obsolete.
