### ISSUE TITLE
Separate mentors and mentees in DB? 

### ISSUE THREAD

**Issue by jpabadir** [jpabadir/pace-c#264]
This is just an idea for the future that would allow us to iterate through the mentees without having to fetch the mentors as well. Instead of having:

```
users: {
allUsers
}
```
Maybe we should do:
```
users: {
mentors: { mentors }, 
mentees: { mentees }
}
```

**Comment by katmartel** [comment]
Splitting the users based on user-type could be beneficial, for sure! It might be useful to discuss this during the meeting tomorrow
