### ISSUE TITLE
Incorporate client feedback into project

### ISSUE THREAD

**Issue by aleksssk** [jpabadir/pace-c#287]
Incorporate client feedback into project (as per pr #284 )

**Comment by katmartel** [comment]
Please do the 3 tasks as outlined in the comment: https://github.com/jpabadir/pace-c/pull/284#issue-522663310
As well as the routing to a new page for the 'forgot your password' feature.
The client recommends creating a link out of the words "Forgot Your Password?", routing to a 'Forgot Your Password' page, where the user is then required to enter their email address, and then sends an email to that user to reset their password.
