### ISSUE TITLE
Create video for project

### ISSUE THREAD

**Issue by aleksssk** [jpabadir/pace-c#289]
Due tues 24th, go through kat's list, and make it max 5min. Start with bigger features then do smaller features.

**Comment by jpabadir** [comment]
Do you remember, like I do, that we agreed that this should take about 20 minutes? This means this is not a task. As per [the course website](https://github.com/brandongk-ubco/gitstats/blob/develop/docs/technical/issues.md), tasks, chores and exploration tasks (any officially labelled issue), take between 2 and 4 hours. Please remove the label.

**Comment by aleksssk** [comment]
Oh, I think i just automatically put it as a task since im used to making issues then making it tasks while i wrote the description
