### ISSUE TITLE
Fix login form error messages and pop-up wording (on login form as well)

### ISSUE THREAD

**Issue by jpabadir** [jpabadir/pace-c#324]

**Comment by jpabadir** [comment]
Make error messages more descriptive (for instance email and password missing messages)

**Comment by wrc9817** [comment]
From peer testing report:
- When signing in, if the user does not enter anything for email and password, it just says "please input something" for both fields, and then a pop-up that says "the email address is badly formatted" however both fields are blank. (login page)
- From the above point, we should change "please input something" to "please input password" or "please input email", for the red text that pops up at the bottom of the field if the user does not enter an email address in the login page. (login page)
- If the user enters a incorrect username and password, the website creates a popup that is "wordy" and maybe difficult to understand. (login page)
- We should make different messages depending on whether the user did not enter any information in login screen (password/email) or if the user entered information but the information is wrong/does not have an account. (login page)
- From above points, change the login pop up messages depending on what is and is not filled in. Change the red text that popups at the bottom of the field depending on what is and is not filled in. (login page)
