### ISSUE TITLE
Prepare your presentation parts

### ISSUE THREAD

**Issue by jpabadir** [jpabadir/pace-c#495]
Out of the points in the [presentation requirements](https://people.ok.ubc.ca/bowenhui/499/finalReport.html), make slides for the following two, which you'll be presenting:

1. A brief description of the software you are building
2. The requirements, design, and test results of your software

Make sure you read the requirements carefully before starting on this task. In the slides, you can include any prototypes we had made, diagrams, previous descriptions we used, etc. Anything that helps you present these two things. Assume the video doesn't give info about them. 

Wait for Aleks to send you the Google Slides link on Discord. Please build these two sections after each of the two appropriate marker slides made by Aleks to demarcate the various sections.

**Comment by wrc9817** [comment]
Link:https://docs.google.com/presentation/d/1sVmy_5QQ0siq0K7j4UhdK43ZlHqF2yE5FaPrWn5iHbU/edit#slide=id.gc79c3884c2_0_64 
Slides 2-8
